### PR TITLE
allow using babel to transpile future javascript-based widgets

### LINKED ISSUE #121: Add support for ES6 via Babel
Fat arrows, string templates and more would be really nice to use with this project. I'm interested in putting work into this if a PR would be welcome.

### PR DESCRIPTION
**Pull request by hawkrives**
Added a dependency on `babel-core`, then just transpile every non-coffeescript widget with Babel.

Should close #121.

### CODE REVIEW

**Comment by hawkrives** [comment]
Oh wait. I forgot to include the babel code in the commit.

**Comment by hawkrives** [comment]
@felixhageloh: Where would you like new dependencies to go? `server/release/node_modules`, and re-build whichever script grunt controls?

**Comment by felixhageloh** [comment]
it depends - if the dependency can be browserified then there is no need to add it to `server/release/node_modules`. If not then you need to add it there and make sure to add it to the 'external' option in the grunt browsrify config

**Comment by hawkrives** [comment]
I believe it's browserifiable. I'll re-compile it and check (also look at file sizes).

**Comment by hawkrives** [comment]
It does appear to be browserifiable.

```
no babel:  server.js   2.6M
babel:     server.js    65K
```

Seems reasonable to me.

**Comment by felixhageloh** [comment]
wait, the version with babel is smaller than _without_? 
Generally, yeah I would commit the bundle

**Comment by hawkrives** [comment]
Er, no. I seem to have flipped the two labels. 

I'll commit the updated bundle later today!

**Comment by hawkrives** [comment]
One thing I noticed: when I run `grunt release`, the file `server/release/public/main.js` ends up quite different. Mostly, it's just underscores being moved around on variable names, but there are some functions that ended up with different arguments, and even a switch statement that changed.

Should I commit that updated file?

```diff
diff --git a/server/release/public/main.js b/server/release/public/main.js
index 8c2e6f1..3b4cb8e 100644
--- a/server/release/public/main.js
+++ b/server/release/public/main.js
@@ -54,22 +54,22 @@ getChanges = function() {
 };
 
 initWidgets = function(widgetSettings) {
-  var id, settings, widget, _results;
-  _results = [];
+  var id, results, settings, widget;
+  results = [];
   for (id in widgetSettings) {
     settings = widgetSettings[id];
     if (widgets[id] != null) {
       widgets[id].destroy();
     }
     if (settings === 'deleted') {
-      _results.push(delete widgets[id]);
+      results.push(delete widgets[id]);
     } else {
       widget = Widget(settings);
       widgets[widget.id] = widget;
-      _results.push(initWidget(widget));
+      results.push(initWidget(widget));
     }
   }
-  return _results;
+  return results;
 };
 
 initWidget = function(widget) {
@@ -97,15 +97,15 @@ bail = function() {
 };
 
 logError = function(serialized) {
-  var e, err, errors, _i, _len, _results;
+  var e, err, errors, i, len, results;
   try {
     errors = JSON.parse(serialized);
-    _results = [];
-    for (_i = 0, _len = errors.length; _i < _len; _i++) {
-      err = errors[_i];
-      _results.push(console.error(err));
+    results = [];
+    for (i = 0, len = errors.length; i < len; i++) {
+      err = errors[i];
+      results.push(console.error(err));
     }
-    return _results;
+    return results;
   } catch (_error) {
     e = _error;
     return console.error(serialized);
@@ -122,9 +122,9 @@ window.onload = init;
 /* toSource by Marcello Bastea-Forte - zlib license */
 module.exports = function(object, filter, indent, startingIndent) {
     var seen = []
-    return walk(object, filter, indent === undefined ? '  ' : (indent || ''), startingIndent || '', seen)
+    return walk(object, filter, indent === undefined ? '  ' : (indent || ''), startingIndent || '')
 
-    function walk(object, filter, indent, currentIndent, seen) {
+    function walk(object, filter, indent, currentIndent) {
         var nextIndent = currentIndent + indent
         object = filter ? filter(object) : object
         switch (typeof object) {
@@ -132,10 +132,9 @@ module.exports = function(object, filter, indent, startingIndent) {
                 return JSON.stringify(object)
             case 'boolean':
             case 'number':
+            case 'function':
             case 'undefined':
                 return ''+object
-            case 'function':
-                return object.toString()
         }
 
         if (object === null) return 'null'
@@ -151,12 +150,12 @@ module.exports = function(object, filter, indent, startingIndent) {
 
         if (Array.isArray(object)) {
             return '[' + join(object.map(function(element){
-                return walk(element, filter, indent, nextIndent, seen.slice())
+                return walk(element, filter, indent, nextIndent)
             })) + ']'
         }
         var keys = Object.keys(object)
         return keys.length ? '{' + join(keys.map(function (key) {
-            return (legalKey(key) ? key : JSON.stringify(key)) + ':' + walk(object[key], filter, indent, nextIndent, seen.slice())
+            return (legalKey(key) ? key : JSON.stringify(key)) + ':' + walk(object[key], filter, indent, nextIndent)
         })) + '}' : '{}'
     }
 }
@@ -166,7 +165,6 @@ var KEYWORD_REGEXP = /^(abstract|boolean|break|byte|case|catch|char|class|const|
 function legalKey(string) {
     return /^[a-z_$][0-9a-z_$]*$/gi.test(string) && !KEYWORD_REGEXP.test(string)
 }
-
 },{}],4:[function(require,module,exports){
 var cachedWallpaper, getWallpaper, getWallpaperSlices, loadWallpaper, renderWallpaperSlice, renderWallpaperSlices;
 
@@ -184,9 +182,9 @@ window.addEventListener('onwallpaperchange', function() {
 });
 
 exports.makeBgSlice = function(canvas) {
-  var _ref;
+  var ref;
   canvas = $(canvas);
-  if (!((_ref = canvas[0]) != null ? _ref.getContext : void 0)) {
+  if (!((ref = canvas[0]) != null ? ref.getContext : void 0)) {
     throw new Error('no canvas element provided');
   }
   canvas.attr('data-bg-slice', true);
@@ -208,10 +206,10 @@ getWallpaper = function(callback) {
   }
   cachedWallpaper.loading = true;
   return loadWallpaper(function(wallpaper) {
-    var _i, _len, _ref;
-    _ref = getWallpaper.callbacks;
-    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
-      callback = _ref[_i];
+    var i, len, ref;
+    ref = getWallpaper.callbacks;
+    for (i = 0, len = ref.length; i < len; i++) {
+      callback = ref[i];
       callback(wallpaper);
     }
     getWallpaper.callbacks.length = 0;
@@ -231,13 +229,13 @@ getWallpaperSlices = function() {
 };
 
 renderWallpaperSlices = function(wallpaper, slices) {
-  var canvas, _i, _len, _results;
-  _results = [];
-  for (_i = 0, _len = slices.length; _i < _len; _i++) {
-    canvas = slices[_i];
-    _results.push(renderWallpaperSlice(wallpaper, canvas));
+  var canvas, i, len, results;
+  results = [];
+  for (i = 0, len = slices.length; i < len; i++) {
+    canvas = slices[i];
+    results.push(renderWallpaperSlice(wallpaper, canvas));
   }
-  return _results;
+  return results;
 };
 
 renderWallpaperSlice = function(wallpaper, canvas) {
@@ -276,7 +274,7 @@ module.exports = function(implementation) {
   rendered = false;
   defaultStyle = 'top: 30px; left: 10px';
   init = function() {
-    var issues, k, v, _ref;
+    var issues, k, ref, v;
     if ((issues = validate(implementation)).length !== 0) {
       throw new Error(issues.join(', '));
     }
@@ -286,7 +284,7 @@ module.exports = function(implementation) {
     }
     cssId = api.id.replace(/\s/g, '_space_');
     if (!((implementation.css != null) || (typeof window !== "undefined" && window !== null))) {
-      implementation.css = parseStyle((_ref = implementation.style) != null ? _ref : defaultStyle);
+      implementation.css = parseStyle((ref = implementation.style) != null ? ref : defaultStyle);
       delete implementation.style;
     }
     return api;
@@ -383,7 +381,7 @@ module.exports = function(implementation) {
     var e;
     if (error) {
       contentEl.innerHTML = error;
-      console.error("" + api.id + ":", error);
+      console.error(api.id + ":", error);
       return rendered = false;
     }
     try {
@@ -408,16 +406,16 @@ module.exports = function(implementation) {
     }
   };
   loadScripts = function(domEl) {
-    var s, script, _i, _len, _ref, _results;
-    _ref = domEl.getElementsByTagName('script');
-    _results = [];
-    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
-      script = _ref[_i];
+    var i, len, ref, results, s, script;
+    ref = domEl.getElementsByTagName('script');
+    results = [];
+    for (i = 0, len = ref.length; i < len; i++) {
+      script = ref[i];
       s = document.createElement('script');
       s.src = script.src;
-      _results.push(domEl.replaceChild(s, script));
+      results.push(domEl.replaceChild(s, script));
     }
-    return _results;
+    return results;
   };
   parseStyle = function(style) {
     var scopedStyle;
```

**Comment by hawkrives** [comment]
*ping @felixhageloh* – any thoughts?

**Comment by felixhageloh** [comment]
Re. the built main.js: could be that you were having a different version of coffeescript, so the compiled result looks a bit different. If it still works I wouldn't worry about it. 
Btw this one just came in as well https://github.com/felixhageloh/uebersicht/pull/163

**Comment by hawkrives** [comment]
Ya, I'll take a peek at it. You wouldn't happen to have pushed that hypothetical in-progress branch anywhere, would you?

**Comment by hawkrives** [comment]
I'm happy with it, too; it's the same as mine, just updated for Babel 6. I'll close in favor of it.

**Pull request closed without merging**
