### PR TITLE
Babel6 integration

### PR DESCRIPTION
**Pull request by jakobwesthoff**
Integrated Babel 6.x. Each JavaScript Widget is now preprocessed by Babel using the es2015 preset. This allows for backwards compatibility with older js based widgets as well as new ones using ES6/ES2015 features.

The Babel transpiler was added as an external _release_ depdency

### CODE REVIEW

**Comment by felixhageloh** [comment]
nice looks good! 
I'm a bit undecided whether I should merge this in right now: I'm working on a new release were I changed the build process (basically completely ditched Grunt). I'm hoping to release very soon so I could merge this manually afterwards. If I understand correctly, aside from installing the dependencies, the main code change required is inside widget_loader.coffee?

**Comment by jakobwesthoff** [comment]
Yes essentially it is a change to the `widget_loader.coffee`. It should be quite easy to merge it manually. However don't forget to make the `babel-core` and `babel-preset-es2015` package available to the *server* as well.

As I am currently writing some widgets for my desktop I am thinking about creating some sort of loader system for *frameworks*, which then could be accessed by *all*  widgets somehow.

Currently I am thinking about a middleware, which allows the creation and loading of `something.framework` packages. Those could then expose library stuff in a well defined manner, which could be made accessible to any other widget afterwards.

Furthermore I am thinking about a *command* aka. *route*, which allows to directly proxy arbitrary XHR to outside resources (like in my case a jira for example).

What do you think about those _extensions_? Would you be interested in something like this? Should I wait with the integration until your new release is out or is there already some branch I could build upon?

**Comment by felixhageloh** [comment]
Ok great, thanks - I think I will merge this in manually then!

About frameworks: My current idea to solve this problem is to use CommonJS so people can just npm install and `require` any libraries they need (as long as they work in the browser). This would mean every widget would get [browserified](http://browserify.org) before it gets loaded into the webview. 

The slight drawback would be that libraries that are shared among widgets would be duplicated. The big advantage is that widgets are entirely self-contained tho. 

To make sure I understand your second suggestion correctly: You would like to have a sort of proxy to access third party APIs without running into CORS issues?

And finally: this is my current working branch https://github.com/felixhageloh/uebersicht/tree/multiple-screens-ws. It is pretty close to being finished - mostly specs missing now. Having said that, I think it is still better to branch of master for pull requests, because having co-dependent branches can become quite messy

**Comment by jakobwesthoff** [comment]
Using `npm` and CommonJS modules to solve the framework problem is a lot more elegant, than what I had in mind. (I just didn't want to restructure your whole building process ;). I don't see a problem, that each widgets gets bigger due to the bundling process, as they are transferred through loopback only.

 Regarding my second suggestion: Yes exactly. I am currently having trouble taking to a service, which does not allow for CORS by itself. Therefore I would implement some sort of *proxy* route to solve that problem.

**Comment by Egoscio** [comment]
Hello,

I'm new to uebersicht and so far it's love at first sign. Only problem I have is using ES6 features in my widgets. Is Babel officially supported in the downloadable version on http://tracesof.net/uebersicht/ ? If so, does it require somehow being enabled? I did a quick search in the repository for "babel" and nothing came up, so I was wondering how the integration works.

Thank you,

- Egoscio

**Comment by felixhageloh** [comment]
@Egoscio indeed this feature has not been released yet and it's only available in this branch. I'm hoping to release it very soon!

**Comment by felixhageloh** [comment]
@jakobwesthoff great, that validates my idea then.

Regarding the proxy: so far I've always pointed people towards using a shell command (curl etc) to solve this issue. I can imagine that it would be a lot easier and convenient for many if they could just do Ajax requests from JavaScript, tho. So if you have any ideas, I'm curious!

**Comment by Egoscio** [comment]
@felixhageloh Okay, looking forward to it's release :) I'll try building this branch for testing until then.

**Comment by CarlosMed** [comment]
For one of my widgets I've just been using the jquery Ajax request to option API info. I also ran a tests between using the geolocation api and some type of geocoder api to obtain the longitude and latitude and then send it to forcast.io that upon waking the computer from sleep/login/restart it manages to get gelocation based widgets after connection to wifi much faster than having to call an external Api.

**Comment by felixhageloh** [comment]
@jakobwesthoff I've updated master. If you want you can make a new pull request - that way you will actually show up as a contributor :). Otherwise I can merge this by hand as discussed before.
It should be not too hard to adapt the PR - the code has moved to `parseWidget.js` and you don't have to commit built files anymore. 

Anyone interested in testing the new version btw? I can send a link

**Comment by alexisvincent** [comment]
Any info on this?

**Comment by felixhageloh** [comment]
@alexisvincent not sure if this is still amerceable (it needs some work in any case), but I am currently working on this feature!

**Comment by balupton** [comment]
> About frameworks: My current idea to solve this problem is to use CommonJS so people can just npm install and require any libraries they need (as long as they work in the browser). This would mean every widget would get browserified before it gets loaded into the webview.

Did this get done? I'm new to Ubersicht so wouldn't know.

If it has, people wanting to use ES6 features can just use the [`browser` field](https://github.com/bevry/editions/wiki/Fields) to point to the published compiled edition (if the browserify stuff was also done).

**Comment by felixhageloh** [comment]
sorry for the late response! It has basically been done - you can use `require` in coffeescript widgets and you can use ES6 + JSX when using a `.jsx` extension for your widget ([see example](https://gist.github.com/felixhageloh/94d5dd41cc5ff8a633900ffb28bd195a)). The latter is still in beta btw. 

I will close this PR for now

**Pull request closed without merging**
