### PR TITLE
Add Xcode build instructions

### PR DESCRIPTION
**Pull request by dnicolson**
Not sure if these instructions are best practice, but it might save someone some time.

### CODE REVIEW

**Comment by felixhageloh** [comment]
thanks that's something that needs improvement still! I'm usually happy enough when I can get Xcode to build for myself, let alone other developers :).

I will have a read through - I think some things can be done even easier (like disabling code signing) - but it's a great start.

Btw, while I have your attention: After merging your previous PR I played a bit with the code. I have a slightly modified version but I'm not sure if it fixes your initial problem. I have a pre-release build here  http://tracesof.net/uebersicht/releases/Uebersicht-0.8.32.app.zip - maybe you can try it quickly and let me know if it works as intended!

**Comment by dnicolson** [comment]
Unfortunately it doesn't solve the problem (I tried putting the code there as well). Not sure why it needs to be in the `change` event handler, I didn't spend too much time on it.

**Comment by felixhageloh** [comment]
Alright I see! Can you describe your setup in more detail? I tried it by replacing my widget folder with a symlink and all seems good

**Comment by dnicolson** [comment]
The widgets directory is symlinked to `~/Dropbox/Mackup/Library/Application Support/Übersicht/widgets` and you just need to edit a widget to trigger a duplicate widget.

**Comment by felixhageloh** [comment]
I see ... so the weird thing is that when I call normalize() on a file path I start having duplicated widgets just like you. Another person that tried a pre-release version with normalize started having the same problem. Once I removed the normalize() it was fixed for both of us. So basically it is the exact opposite of what you are experiencing. I wonder if this comes down to some OS setting ... 
What version of OS X are you on btw?

**Comment by felixhageloh** [comment]
k I think I might have gotten to the bottom of this. Can you try this version http://tracesof.net/uebersicht/releases/Uebersicht-0.8.33.app.zip  ?

**Comment by dnicolson** [comment]
This new version works correctly with symlinks. Although this version loads the `~/.bash_profile` file for some reason and all widgets were failing to load until I fixed a "command not found" error. I use fish so the `~/.bash_profile` file was outdated.

**Comment by felixhageloh** [comment]
Ok great! 
About ~/.bash_profile: I've added another feature to this build. People were complaining that their env wasn't available when running commands, so I thought this would be solved by spawning the bash process that runs commands as a login shell (which automatically loads ~/.profile etc.)

Would you say that your issue was caused by a 'broken' bash_profile or do you think this approach has some fundamental problems?

**Comment by dnicolson** [comment]
Is it possible to redirect STDOUT/STDERR to /dev/null? It's possible some `.bash_profile` might echo normal output.

rbenv looks at the  [`$SHELL`](https://github.com/rbenv/rbenv/blob/d51f6d437690c8b7f7098a613caaea835658d40e/libexec/rbenv-init#L45) environment variable, but that might not be available depending on where in the code you're reading it from.

**Comment by felixhageloh** [comment]
I left it out of the last release since there seems to be more complex than I thought :). I'll look into the issues you mentioned next time I tackle it.

Now, about this PR: to disable code signing, I think you can do two things. In project settings disable code signing (set to 'none'):

screen shot 2016-03-04 at 9 56 24


And then in Build Phases, disable (by commenting out the shell script) or remove the last step:
screen shot 2016-03-04 at 9 58 18


Let me know if you think this is easer than your approach and if you want to incorporate it into the Readme.

Oh and one important last info: I'm using Xcode 6.4 to build Übersicht, because I still support OS X 10.9

**Comment by dnicolson** [comment]
Thanks for the tip, I've updated the code signing instructions.

**Comment by felixhageloh** [comment]
awesome, thanks!

**Pull request merged**
