### PR TITLE
Allow specifying refreshFrequency as a string (10ms, 5s, etc)

### LINKED ISSUE #94: Allow specifying refreshFrequency as a string
For instance, `"1 hour"` or `"1 second"`, or even `"1 min"`.

I keep having to calculate the number of milliseconds in some time period, and then I can never remember how long of a duration I've specified in the future.

I suppose that the second bit could be simplified by me adding a comment to the line, but would you be opposed to a PR that added support for english time spans?

### PR DESCRIPTION
**Pull request by hawkrives**
It's parsed by the `ms` package on npm. (https://www.npmjs.com/package/ms)

I think that it passes all the tests.

(Closes #94)

### CODE REVIEW

**Comment by felixhageloh** [comment]
Thanks, looks good! I'll see I've I can get this out this week! If you have some time, you could add a small spec for this. This snippet from `server/spec/frontend/widget_spec.coffee` should get you started:

```
describe 'with a refreshFrequency', ->
    beforeEach ->
      widget = Widget
        command: 'some-command',
        id     : 'foo',
        refreshFrequency: 100
      widget.create()

    it 'refreshes with that frequency', ->
      jasmine.clock().install()
      server.respondToWidget "foo", 'stuff'
      server.autoRespond = true

      spyOn(widget, 'run').and.callThrough()
      spyOn(widget, 'render').and.callThrough()

      widget.start()
      jasmine.clock().tick 250
      expect(widget.run.calls.count()).toBe 3
      expect(widget.render.calls.count()).toBe 3
```

**Comment by hawkrives** [comment]
@felixhageloh Do you still want me to try and add that test?

**Comment by felixhageloh** [comment]
Would be great! In any case I think I will merge this in with the next release

**Comment by felixhageloh** [comment]
I noticed that specs are a mess now (many outdated package dependencies) I will just merge this in for now.
I'm working on a larger release and I will have to refactor many specs anyway

**Comment by hawkrives** [comment]
Thanks!

**Pull request merged**
